### ISSUE TITLE
Use keyboard!

### ISSUE THREAD

**Issue by afonsopacifer** [afonsopacifer/react-pomodoro#10]
EX: Press space for play ou pause the time :)

**Comment by shakegioh** [comment]
We should define which shortcut is better for toggle modes, initially I thought: Arrows, but i don't think it's the best option since it could happen unintentionally, so maybe use Ctrl+[qwe] could be the way, what you think?

**Comment by afonsopacifer** [comment]
I thought only:
- `SPACE` - For Play or Pause the timer

But,
Ctrl+Arrows keys is cool 👍

**Comment by cauealves** [comment]
I really prefer to use `SPACE`.

People are much more accustomed to using it. For play or pause anything.

@shakegioh I see has an opened pull request https://github.com/afonsopacifer/react-pomodoro/pull/30 by you, the works are finished? Do not you think it would be best to use `SPACE` instead of `ARROWS`?

**Comment by shakegioh** [comment]
@cauealves the space is being used to play / pause. The ctrl + arrows shortcuts toggle between modes (Code / Social / Coffee).

**Comment by cauealves** [comment]
Nice @shakegioh, I did not get to see all changes but the pull request are accepted by Afonso.

The issue can be closed. ;)

**Comment by cauealves** [comment]
This issue was solved on https://github.com/afonsopacifer/react-pomodoro/pull/30
